# Global options for the build
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Authenticate Docker for both projects
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud auth configure-docker --quiet' ]

  # Build and push container2 for your project
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/assi-427619/a3-artifact/dbhavsar214-container2/acon2:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/assi-427619/a3-artifact/dbhavsar214-container2/acon2:latest']

  # Get credentials for your project's cluster and deploy container2
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cluster-3 --zone us-central1-c --project assi-427619

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f container2-deployment.yaml
        kubectl set image deployment/container2-deployment acon2=us-central1-docker.pkg.dev/assi-427619/cluste-3/acon2:latest
        kubectl rollout status deployment/container2-deployment
