apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: divy214/acon2:latest
        ports:
        - containerPort: 6001
        env:
        - name: PORT
          value: '6001'
        - name: FILE_DIRECTORY
          value: "/divy_PV_dir"
        volumeMounts:
        - name: container2-pvc
          mountPath: /divy_PV_dir
      volumes:
      - name: container2-pvc
        persistentVolumeClaim:
          claimName: container2-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 90
      targetPort: 6001
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi